# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0002_auto_20171011_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritance.Place')),
                ('customers', models.ManyToManyField(related_name='providers', related_query_name='provider', to='inheritance.Place')),
            ],
            bases=('inheritance.place',),
        ),
        migrations.CreateModel(
            name='Midliner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inheritance.champion',),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inheritance.champion',),
        ),
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['rank'], 'verbose_name': '챔피언'},
        ),
    ]
